import type { AdSpec } from './types'

export const ADS: AdSpec[] = [
  {
    id: 'ram-insurance',
    productName: 'RAM Insurance™',
    headline: 'Is Your RAM Protected? (No.)',
    body: 'Your RAM is currently uninsured. This is legal in only 3 states. Accidents happen every 0.4 seconds — a stray Chrome tab, a rogue spreadsheet, a sneeze near the tower. Without RAM Insurance™, you are financially and emotionally exposed. Bundle with Cache Insurance™ and save absolutely nothing.',
    price: '$299/mo — first month 92% off, as a treat!',
    monthlyCost: 24.99,
    ctaLabel: 'INSURE MY MEMORY NOW',
    closeStyle: 'decoy',
    theme: 'urgent',
  },
  {
    id: 'printer-ink',
    productName: 'PrinterInkPrime+',
    headline: 'Your Printer Ink Is Running Low',
    body: 'We know you do not own a printer. We checked. We do not care. Subscribe today and receive a monthly cartridge of ink for a device that does not exist, shipped directly to an address we are still working on obtaining.',
    price: '$89.99/cartridge — subscribe & "save"',
    monthlyCost: 19.99,
    ctaLabel: 'YES, SHIP THE INK',
    closeStyle: 'tiny',
    theme: 'friendly',
  },
  {
    id: 'wondows-pro',
    productName: 'Wondows12 Pro Ultimate Home Basic Premium Starter Edition',
    headline: 'Unlock The REAL Wondows12',
    body: 'You are currently using Wondows12 Regular, which is legally required to disappoint you. Upgrade to Wondows12 Pro Ultimate Home Basic Premium Starter Edition to unlock features such as: the taskbar, closing this ad faster, and the number 12.',
    price: '$349.99/yr (or 12 easy payments of $349.99)',
    monthlyCost: 34.99,
    ctaLabel: 'UPGRADE MY LIFE',
    closeStyle: 'delayed',
    theme: 'corporate',
  },
  {
    id: 'sub-manager',
    productName: 'Subscription Manager Pro',
    headline: 'Tired Of Too Many Subscriptions?',
    body: 'Subscription Manager Pro helps you take control by automatically subscribing you to two additional subscription managers, which will each subscribe you to two more. This is how we grow. This is how we all grow.',
    price: '$44.99/mo — "saves you money"',
    monthlyCost: 44.99,
    ctaLabel: 'TAKE CONTROL',
    closeStyle: 'decoy',
    theme: 'cursed',
  },
  {
    id: 'cloudbin',
    productName: 'CloudBin®',
    headline: 'Never Lose Your Garbage Again',
    body: 'Every file you have ever deleted deserves a second chance at existing forever. CloudBin® backs up your Recycle Bin to the cloud, syncing your trash across all devices, all time zones, and several emotions.',
    price: '$59.99/mo per 1GB of garbage',
    monthlyCost: 29.99,
    ctaLabel: 'BACK UP MY TRASH',
    closeStyle: 'corner',
    theme: 'neon',
  },
  {
    id: 'cursor-warranty',
    productName: 'Extended Cursor Warranty',
    headline: 'What If Your Cursor... Broke?',
    body: 'Cursors are fragile. One day it points, the next day — who knows. Protect your arrow-shaped friend with an Extended Cursor Warranty, covering blinking malfunctions, wrong-direction pointing, and existential drift.',
    price: '$19.99/mo, terms apply, terms unavailable',
    monthlyCost: 14.99,
    ctaLabel: 'PROTECT MY CURSOR',
    closeStyle: 'tiny',
    theme: 'urgent',
  },
  {
    id: 'cpu-oxygen',
    productName: 'Premium CPU Oxygen',
    headline: 'Is Your CPU... Breathing?',
    body: 'Introducing Premium CPU Oxygen: artisanal, small-batch air, hand-fanned by former wind farm employees and delivered directly into your case via a small, expensive tube. Your processor deserves better than the air it was born with.',
    price: '$399/mo — first month 92% off, as a treat!',
    monthlyCost: 39.99,
    ctaLabel: 'LET IT BREATHE',
    closeStyle: 'delayed',
    theme: 'cursed',
  },
  {
    id: 'pc-horoscope',
    productName: 'MachineStars™ PC Horoscopes',
    headline: 'Mercury Is In Retrograde. So Is Your Motherboard.',
    body: 'Your computer was born under the sign of Compaq, meaning today is an excellent day for blue screens and a terrible day for saving documents. Subscribe for daily horoscopes tailored to your exact hardware\'s emotional state.',
    price: '$14.99/mo for cosmic clarity',
    monthlyCost: 14.99,
    ctaLabel: 'READ MY FUTURE',
    closeStyle: 'corner',
    theme: 'friendly',
  },
  {
    id: 'blocker-blocker',
    productName: 'AdBlock Blocker Blocker Pro',
    headline: 'Someone Is Blocking Your Ad Blockers',
    body: 'We detected that your ad blocker is being blocked by our anti-ad-blocker, which itself may be blocked by illegal third-party anti-anti-ad-blockers. Subscribe to AdBlock Blocker Blocker Pro to legally re-block the blockers.',
    price: '$29.99/mo, recursive billing',
    monthlyCost: 29.99,
    ctaLabel: 'UNBLOCK THE BLOCK',
    closeStyle: 'decoy',
    theme: 'urgent',
  },
  {
    id: 'blinker-fluid',
    productName: 'Blinker Fluid Home Delivery',
    headline: 'Your Cursor Blink Rate Is Critically Low',
    body: 'Industry experts (us) recommend refilling your cursor\'s blinker fluid every 30 days to maintain that crisp, professional flicker. Skipping refills may result in a solid, unblinking cursor, which is illegal in most word processors.',
    price: '$24.99/mo per quart',
    monthlyCost: 24.99,
    ctaLabel: 'REFILL NOW',
    closeStyle: 'tiny',
    theme: 'corporate',
  },
  {
    id: 'icon-nft',
    productName: 'DesktopChain™ Icon NFTs',
    headline: 'Own Your Own Desktop Icons. Legally. Sort Of.',
    body: 'That Recycle Bin icon? You have been using it for free this whole time. Mint it as an NFT today and finally own a blockchain-verified copy of an icon you already had, that anyone can still right-click and copy.',
    price: '$49.99/mo minting fee (fees may increase)',
    monthlyCost: 49.99,
    ctaLabel: 'MINT MY TRASH CAN',
    closeStyle: 'delayed',
    theme: 'cursed',
  },
  {
    id: 'font-gym',
    productName: 'Font Gym Membership',
    headline: 'Is Comic Sans... Out Of Shape?',
    body: 'Fonts need exercise too. A Font Gym Membership keeps your typefaces limber, your serifs toned, and your kerning tight. Unused fonts may atrophy and be quietly replaced with Wingdings while you sleep.',
    price: '$17.99/mo, no annual contract (there is an annual contract)',
    monthlyCost: 17.99,
    ctaLabel: 'PUMP MY FONTS',
    closeStyle: 'corner',
    theme: 'friendly',
  },
  {
    id: 'wifi-vitamins',
    productName: 'Wi-Fi Vitamins',
    headline: 'Boost Your Signal From The Inside',
    body: 'Doctors (network engineers, probably) recommend a daily dose of Wi-Fi Vitamins to support healthy bar count, immune your router against interference, and give your signal that extra bounce it deserves. Not evaluated by anyone.',
    price: '$12.99/mo per bottle of bars',
    monthlyCost: 12.99,
    ctaLabel: 'BOOST MY BARS',
    closeStyle: 'tiny',
    theme: 'neon',
  },
  {
    id: 'silence-suite',
    productName: 'Notification Silence Suite™ Pro',
    headline: 'Tired Of Notifications? Subscribe To Stop Them!',
    body: 'Ironic, we know. Subscribe to Notification Silence Suite™ Pro to reduce the number of ads interrupting you, and receive a new pop-up every 30 seconds reminding you that it is working.',
    price: '$39.99/mo for peace and quiet',
    monthlyCost: 39.99,
    ctaLabel: 'SILENCE EVERYTHING',
    closeStyle: 'decoy',
    theme: 'urgent',
  },
]
